# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
metadata:
  name: "{{ .managedCluster.name }}"
baseDomain: {{ .managedCluster.aws.baseDnsDomain }}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      rootVolume:
        iops: 4000
        size: 100
        type: io1
      type: m5.4xlarge
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.4xlarge
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork: 
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: {{ .managedCluster.aws.region }}
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
{{ .managedCluster.sshPublicKey | indent 4 }}
