# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
metadata:
  name: "{{ .managedCluster.name }}"
baseDomain: {{ .managedCluster.vsphere.baseDnsDomain }}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    vsphere:
      cpus:  4
      coresPerSocket:  2
      memoryMB:  16384
      osDisk:
        diskSizeGB: 120
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3
  platform:
    vsphere:
      cpus:  4
      coresPerSocket:  2
      memoryMB:  16384
      osDisk:
        diskSizeGB: 120
platform:
  vsphere:
    vCenter: {{ .managedCluster.vsphere.vcenter }}
    username: {{ .managedCluster.vsphere.username }}
    password: {{ .managedCluster.vsphere.password }}
    datacenter: {{ .managedCluster.vsphere.datacenter }}
    defaultDatastore: {{ .managedCluster.vsphere.datastore }}
    cluster: {{ .managedCluster.vsphere.cluster }}
    apiVIP: {{ .managedCluster.vsphere.apiVIP }}
    ingressVIP: {{ .managedCluster.vsphere.ingressVIP }}
    network: {{ .managedCluster.vsphere.network }}
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
{{ .managedCluster.sshPublicKey | indent 4 }}
