# Copyright Contributors to the Open Cluster Management project

managedCluster:
  installAttemptsLimit: 1 #Number of attempt install, default 1
  master: 
    replicas: 3 #Number of master node, default 3
  worker:
    replicas: 3 #Number of worker node, default 3
  name: #<cluster-name>, this value is overwritten by the --name parameter
  cloud: vsphere # clouds values can be aws, azure, gcp, openstack, vsphere
  vendor: OpenShift
  ocpImage: # ocp image (ie: quay.io/openshift-release-dev/ocp-release:4.3.40-x86_64)
  addons:
    applicationManager:
      enabled: true
    policyController:
      enabled: true
    searchCollector:
      enabled: true
    certPolicyController:
      enabled: true
    iamPolicyController:
      enabled: true
  sshPublicKey: |-
    Public key
  sshPrivateKey: |-
    -----BEGIN RSA PRIVATE KEY-----
    private key
    -----END RSA PRIVATE KEY-----
  aws:
    baseDnsDomain: # baseDomain of your cluster (ie: mycompany.com)
    awsAccessKeyID:
    awsSecretAccessKeyID:
    region: # Region (ie: us-east-1)
    #Optional
    # master: 
    #   rootVolume:
    #     iops: 4000
    #     size: 100
    #     type: gp2
    #   type: m5.xlarge
    #Optional
    # worker:
    #   rootVolume:
    #     iops: 2000
    #     size: 100
    #     type: gp2
    #   type: m5.xlarge
  azure:
    baseDnsDomain: # baseDomain of your cluster (ie: mycompany.com)
    baseDomainRGN:
    clientID:
    clientSecret:
    tenantID:
    subscriptionID:
    region:
  gcp:
    osServiceAccountJson: |-
      {
        your authentication
      }
    projectID:
    baseDnsDomain:
    region:
  vsphere:
    username:
    password:
    vcenter:
    cacertificate: |-
      -----BEGIN CERTIFICATE-----
      vSphere certificate
      -----END CERTIFICATE-----
    cluster:
    datacenter:
    datastore:
    network:
    baseDnsDomain: # baseDomain of your cluster (ie: mycompany.com)
    apiVIP:
    ingressVIP:
  openstack:
    baseDnsDomain: # baseDomain of your cluster (ie: mycompany.com)
    cloudsYaml: |-
      clouds:
        openstack:
          auth:
    cloud:
    externalNetwork:
    apiFloatingIP:
    ingressFloatingIP:
    masterFlavor:
    workerFlavor:
    machineNetworkCIDR:  
