# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Secret
metadata:
  name: {{ .managedCluster.name }}-ssh-private-key
  namespace: "{{ .managedCluster.name }}"
stringData:
  ssh-privatekey: |- 
{{ .managedCluster.sshPrivateKey | indent 4}}
type: Opaque
